---
- name: Install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php-fpm
    - php-common
    - php-cli
    - php-dev
    - libpcre3-dev
    - php-gd
    - php-curl
    - php-imap
    - php-json
    - php-opcache
    - php-xml
    - php-mbstring
    - php-sqlite3
    - php-apcu